spring:
  datasource:
     name: test
     url: jdbc:mysql://localhost:3306/sharing_bikes
     username: root
     password:
  activemq:
        broker-url: tcp://localhost:61616
        pool:
          enabled: false
redis:
    host: 127.0.0.1
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
